"""Explicit live integration: python3 tests/test_live_torrserver.py --server http://127.0.0.1:8090.

Seeds generated bytes locally. Only this randomly named test torrent is added/removed.
Run on the same machine as TorrServer, with its --webdav flag enabled.
"""
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import secrets
import socket
import socketserver
import struct
import tempfile
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.request import Request, ProxyHandler, build_opener
from urllib.parse import parse_qs, urlsplit

spec = importlib.util.spec_from_file_location('companion', Path(__file__).parents[1] / 'companion.py')
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
opener = build_opener(ProxyHandler({}))


def bencode(value):
    if isinstance(value, int):
        return b'i%de' % value
    if isinstance(value, str):
        value = value.encode()
    if isinstance(value, bytes):
        return str(len(value)).encode() + b':' + value
    if isinstance(value, list):
        return b'l' + b''.join(bencode(v) for v in value) + b'e'
    return b'd' + b''.join(bencode(k) + bencode(value[k]) for k in sorted(value)) + b'e'


class Peer(socketserver.BaseRequestHandler):
    def exact(self, length):
        data = b''
        while len(data) < length:
            block = self.request.recv(length - len(data))
            if not block:
                raise EOFError
            data += block
        return data

    def send(self, value):
        self.request.sendall(struct.pack('!I', len(value)) + value)

    def handle(self):
        self.server.connections += 1
        self.request.settimeout(10)
        try:
            handshake = self.exact(68)
            if handshake[28:48] != self.server.info_hash:
                return
            if not getattr(self, 'initiated', False):
                self.request.sendall(b'\x13BitTorrent protocol' + b'\0' * 8 + self.server.info_hash + b'-IC0001-123456789012')
            pieces = (len(self.server.payload) + self.server.piece_size - 1) // self.server.piece_size
            bits = bytearray((pieces + 7) // 8)
            for index in range(pieces):
                bits[index // 8] |= 1 << (7 - index % 8)
            self.send(b'\x05' + bits)
            self.send(b'\x01')  # unchoke
            while True:
                length = struct.unpack('!I', self.exact(4))[0]
                if length > 65536:
                    return
                message = self.exact(length)
                if message[:1] == b'\x06' and len(message) == 13:
                    piece, begin, count = struct.unpack('!III', message[1:])
                    if count > 16384:
                        return
                    offset = piece * self.server.piece_size + begin
                    self.server.blocks += 1
                    self.send(b'\x07' + struct.pack('!II', piece, begin) + self.server.payload[offset:offset + count])
        except (EOFError, OSError):
            pass


class Tracker(BaseHTTPRequestHandler):
    def log_message(self, *_):
        pass

    def do_GET(self):
        if self.path.startswith('/announce'):
            self.server.announces += 1
            # Initiate a plaintext incoming connection as well. TorrServer may first
            # dial peers using MSE encryption, which this tiny fixture does not implement.
            port = int(parse_qs(urlsplit(self.path).query)['port'][0])
            def connect():
                try:
                    with socket.create_connection(('127.0.0.1', port), timeout=5) as connection:
                        connection.sendall(b'\x13BitTorrent protocol' + b'\0' * 8
                                           + self.server.peer.info_hash + b'-IC0002-123456789012')
                        seed = object.__new__(Peer)
                        seed.request, seed.server, seed.initiated = connection, self.server.peer, True
                        seed.handle()
                except OSError:
                    pass
            threading.Thread(target=connect, daemon=True).start()
            body = bencode({'interval': 1, 'complete': 1, 'incomplete': 0,
                            'peers': socket.inet_aton('127.0.0.1') + struct.pack('!H', self.server.peer_port)})
        else:
            body = self.server.torrent
        self.send_response(200)
        self.send_header('Content-Length', str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--server', required=True)
    args = parser.parse_args()

    def api(endpoint, payload):
        with opener.open(Request(args.server + endpoint, json.dumps(payload).encode(),
                                 {'Content-Type': 'application/json'}), timeout=20) as response:
            body = response.read()
            return json.loads(body) if body else None

    with tempfile.TemporaryDirectory(prefix='iina-torrserver-live-') as temporary:
        peer = socketserver.ThreadingTCPServer(('127.0.0.1', 0), Peer)
        peer.daemon_threads = True
        peer.connections = peer.blocks = 0
        tracker = ThreadingHTTPServer(('127.0.0.1', 0), Tracker)
        tracker.daemon_threads = True
        tracker.announces = 0
        tracker.peer_port = peer.server_address[1]
        tracker.peer = peer
        contents = {'S01E1 — тест.mkv': bytes(range(256)) * 10000,
                    'S01E2.mkv': bytes(reversed(range(256))) * 14000,
                    'S01E2.eng.srt': b'1\n00:00:01,000 --> 00:00:02,000\nTest subtitle\n'}
        peer.payload = b''.join(contents.values())
        peer.piece_size = 256 * 1024
        name = 'IINA-Companion-Test-' + secrets.token_hex(6)
        info = {'name': name, 'piece length': peer.piece_size,
                'pieces': b''.join(hashlib.sha1(peer.payload[p:p + peer.piece_size]).digest()
                                   for p in range(0, len(peer.payload), peer.piece_size)),
                'files': [{'length': len(data), 'path': [filename]} for filename, data in contents.items()]}
        peer.info_hash = hashlib.sha1(bencode(info)).digest()
        torrent_hash = peer.info_hash.hex()
        tracker.torrent = bencode({'announce': 'http://127.0.0.1:%d/announce' % tracker.server_port, 'info': info})
        for service in (peer, tracker):
            threading.Thread(target=service.serve_forever, daemon=True).start()
        helper = None
        added = False
        try:
            assert not api('/viewed', {'action': 'list', 'hash': torrent_hash}), 'Test hash has viewed records'
            assert not any(t['hash'] == torrent_hash for t in api('/torrents', {'action': 'list'}))
            added = True  # Safe to clean this hash even if adding has an unknown HTTP outcome.
            api('/torrents', {'action': 'add', 'link': 'http://127.0.0.1:%d/test.torrent' % tracker.server_port,
                              'title': name, 'category': 'other', 'save_to_db': True})
            now = [1000.]
            cache = module.Companion({'torrserver': args.server, 'cache_dir': temporary + '/cache',
                                       'download_enabled': True, 'cleanup_watched': True, 'cleanup_expired': True,
                                       'token': 'live-test-only-' * 4, 'min_free_bytes': 0,
                                       'max_cache_bytes': 64 * 1024**2}, clock=lambda: now[0])
            catalog = cache.catalog(torrent_hash)
            first = next(f for f in catalog['files'] if f['path'].endswith('S01E1 — тест.mkv'))
            # A prefix exists, but seek into a missing part still plays through TorrServer.
            cache.path(torrent_hash, first['id'], create=True).write_bytes(contents['S01E1 — тест.mkv'][:1000])
            helper = module.make_server(cache, port=0)
            threading.Thread(target=helper.serve_forever, daemon=True).start()
            url = 'http://127.0.0.1:%d/media/%s/%d/test.mkv' % (helper.server_port, torrent_hash, first['id'])
            request_headers = {'Authorization': 'Bearer ' + cache.config['token'],
                               'Range': 'bytes=500-65000'}
            with opener.open(Request(url, headers=request_headers), timeout=30) as response:
                assert response.read() == contents['S01E1 — тест.mkv'][500:65001], 'Partial playback bytes differ'
            print('PASS: real TorrServer playback across cached/missing bytes', flush=True)
            # Remove only the record created by this explicit test playback.
            api('/viewed', {'action': 'rem', 'hash': torrent_hash, 'file_index': first['id']})
            while True:
                task = cache.choose_download()
                if not task:
                    break
                cache.download_one(*task)
            for file in catalog['files']:
                filename = file['path'].rsplit('/', 1)[-1]
                assert cache.path(torrent_hash, file['id']).read_bytes() == contents[filename], 'Cached bytes differ'
            assert not api('/viewed', {'action': 'list', 'hash': torrent_hash}), 'Background download marked viewed'
            print('PASS: all torrent files downloaded byte-for-byte, background leaves viewed unchanged', flush=True)
            restarted = module.Companion(cache.config, clock=lambda: now[0])
            assert restarted.choose_download() is None, 'Restart redownloaded complete files'
            cache.origin = 'http://127.0.0.1:1'
            with opener.open(Request(url, headers={'Authorization': 'Bearer ' + cache.config['token']}), timeout=5) as response:
                assert response.read() == contents['S01E1 — тест.mkv']
            print('PASS: complete cached playback without TorrServer and after state restart', flush=True)
            cache.event({'hash': torrent_hash, 'index': first['id'], 'client': 'test',
                         'event': 'heartbeat', 'position': 95, 'duration': 100})
            now[0] += 121
            cache.event({'hash': torrent_hash, 'index': first['id'], 'client': 'test',
                         'event': 'heartbeat', 'position': 95, 'duration': 100})
            assert not cache.cleanup(), 'Active playback was cleaned'
            cache.event({'hash': torrent_hash, 'index': first['id'], 'client': 'test',
                         'event': 'end', 'position': 95, 'duration': 100})
            assert cache.cleanup() == [(torrent_hash, first['id'])]
            assert len(api('/torrents', {'action': 'list'})) >= 1
            now[0] += 604800
            cache.cleanup()
            assert cache.usage() == 0 and cache.choose_download() is None
            print('PASS: 95% cleanup deferred until stop; week expiry does not refill', flush=True)
        finally:
            print('Seeder diagnostics: announces=%d connections=%d blocks=%d' %
                  (tracker.announces, peer.connections, peer.blocks), flush=True)
            if helper:
                helper.shutdown()
                helper.server_close()
            if added:
                api('/torrents', {'action': 'rem', 'hash': torrent_hash})
                for file_index in range(1, 4):
                    api('/viewed', {'action': 'rem', 'hash': torrent_hash, 'file_index': file_index})
            for service in (tracker, peer):
                service.shutdown()
                service.server_close()


if __name__ == '__main__':
    main()
